# Site settings
title: Notes
description: > # this means to ignore newlines until "baseurl:"
    Notes about Programming, Information Systems, and more
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://notes.mitchmcaffee.com" # the base hostname & protocol for your site
twitter_username:
github_username:  Holyshatots
blog_url: "http://notes.mitchmcaffee.com"
blog_title: My Notes

author: Mitch McAffee

# Build settings
markdown: kramdown

kramdown:
    input: GFM
    syntax_highlighter: rouge
